var list =
    [
        {"quest":"容器属性-方向","anser":"flex-direction:row(水平左开始)，row-reverse(水平右开始)，column(垂直上开始)，column-reverse(垂直下开始)"},
        {"quest":"容器属性-是否换行","anser":"flex-wrap:nowrap(不换行)，wrap(换行第一个在上面)，wrap-reverse(换行第一个在下面)"},
        {"quest":"容器属性-方向换行","anser":"flex-flow:d r"},
        {"quest":"容器属性-主轴排列方式","anser":"justify-content:flex-start,flex-end,center"},
        {"quest":"容器属性-主轴排列方式","anser":"justify-content:space-between(两端对齐,item间隔相等),space-around(两端小间隔，item有相等的大间隔)"},
        {"quest":"容器属性-交叉轴","anser":"align-item:flex-start,flex-end,center"},
        {"quest":"容器属性-交叉轴","anser":"align-item:baseline(已第一个行字对齐)，stretch(铺满高度)"},
        {"quest":"容器属性-多根轴线的对齐","anser":"align-content:flex-start，flex-end,center"},
        {"quest":"容器属性-多根轴线的对齐","anser":"align-content:stretch(每行平均平铺)，"},
        {"quest":"Item属性-顺序","anser":"order:1"},
        {"quest":"Item属性-放大比例","anser":"flex-grow:0(z整个的比例)"},
        {"quest":"Item属性-缩小比例","anser":"flex-shrink:0(咱整个的比例)"},
        {"quest":"Item属性-单个项目","anser":"align-self:auto,flex-start,flex-end,center,baseline,stretch"},
        {"quest":"继承方式-原型","anser":"Sam.prototype = new Person();Sam.prototype.name=''"},
        {"quest":"继承方式-构造函数","anser":"{Person.call(this)[this会在Person中赋值];this.name=''}"},
        {"quest":"继承方式-实例继承","anser":"{son =  new Person();son.name='';return son}"},
        {"quest":"继承方式-实例继承","anser":"{son =  Object.create(new Person());son.name='';return son}"},
        {"quest":"优化-减少请求","anser":"合成js,合成雪碧图，用svg，合成css，减少DNS"},
        {"quest":"优化-代码","anser":"css不使用表达式，js少用全局变量,js缓存DOM节点，避免图片和iFrame等的空Src(空重新加载页面)"},
        {"quest":"优化-图片","anser":"图片优化，懒加载，预加载，放CDN上减少自己服务器压力"},
        {"quest":"优化-缓存","anser":"客户端浏览器缓存(meta中设置缓存页面,最后修改时间，过期时间，Cache-Control:max-age(优先))"},
        {"quest":"优化-缓存","anser":"服务器(js，css，img通过版本号时间戳)"},
        {"quest":"es6-函数定义","anser":"()=>alert(this):this永远指向该函数所在的对象，"},
        {"quest":"es6-class","anser":"super()继承父类，constructor中定义变量"},
        {"quest":"es6-字符模板","anser":"${}"},
        {"quest":"es6-不定参","anser":"(...x)=>{}"},
        {"quest":"es6-promise","anser":"new Promise(resolve,reject);p.reject,p.resolve,p.then,p.all,p.race"},
        {"quest":"vue-react相同","anser":"组件，虚拟DOM,组件间数据流单向，都有检查机制"},
        {"quest":"vue-react不同相同","anser":"检查机制不同(template,object),开发风格(JSX,template),"},
        {"quest":"vue-angular相同","anser":"双向绑定，都有检查机制，都是代码复用"},
        {"quest":"vue-angular不相同","anser":"组件和mvc，更新机制(vue队列)，大小"},
        {"quest":"vue生命周期","anser":"beforeCreate[观察数据,初始化事件],created,[有模板则将模板转函数，无则直接用el作为模板在转]beforeMount,[用函数渲染的vm.$el替换]mounted,"},
        {"quest":"vue生命周期2","anser":"[被观察数据改变]beforeUpdate,[重新渲染函数]updated,beforeDestory,destoryed"},
		{"quest":"判断类型","anser":"typeof obj(number);Object.prototype.toString.apply(obj)(abject Number)"},
		{"quest":"跨域方法","anser":"iframe,postMessage,window.name,jsonp,后台加跨域头"},
		{"quest":"amd,cmd，es6","anser":"amd(requireJs,依赖前置)，cmd(seaJs-就近依赖)，es6就是cmd的实现去掉了头尾"},
		{"quest":"三次握手，四次挥手","anser":"ask,syn,syn。fin,syn,fin,syn"},
		{"quest":"TCP和UDP区别","anser":"必须建立可靠连接和三次握手，直接发送环境不可靠"},
		{"quest":"垃圾回收方法","anser":"标记清除(函数执行完毕后变量清除，给所有变量添加标记，运行中的和闭包中的去除，剩下的被标记的清除"},
		{"quest":"垃圾回收方法","anser":"引用计数(当obj1被obj2引用，obj1会被标记为1，obj2重新引用的时候，obj1被标记为0，为0则清除)"},
		{"quest":"盒子模型","anser":"content-box(在元素外绘制内边距和边框)，border-box(宽高包含了边框和内边距)"},
    ]
